In [ ]:
# ==========================================================================
#                         FEATURE ENGINEERING
#===========================================================================

In [3]:
# Import required libraries

import pandas as pd

In [6]:
# Load cleaned dataset

df = pd.read_csv(
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\01_Data\cleaned_data.csv"
)

df.head()

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,680.0,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [7]:
# Drop unnecessary columns

df = df.drop(columns=[
    "customer_id",
    "signup_date"
])

df.head()

,age,gender,annual_income,education,marital_status,dependents,tenure,contract,payment_method,paperless_billing,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,43,Female,55085.25,college,married,1,2,two_year,electronic_check,1,...,1,1,9.0,0.0,0,0,109.63,16,680.0,0
1,18,Male,60786.11,master,married,1,22,one_year,bank_transfer,1,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,38,Female,73184.32,high_school,widowed,0,3,two_year,credit_card,0,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,44,Male,40923.78,high_school,married,1,6,two_year,bank_transfer,1,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,45,Female,36400.94,bachelor,single,0,9,two_year,credit_card,1,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [8]:
# Convert categorical columns to numeric

df = pd.get_dummies(
    df,
    columns=[
        "gender",
        "education",
        "marital_status",
        "contract",
        "payment_method"
    ],
    drop_first=True
)

df.head()

,age,annual_income,dependents,tenure,paperless_billing,senior_citizen,monthlycharges,totalcharges,num_services,has_phone_service,...,education_master,education_phd,marital_status_married,marital_status_single,marital_status_widowed,contract_one_year,contract_two_year,payment_method_credit_card,payment_method_electronic_check,payment_method_mailed_check
0,43,55085.25,1,2,1,0,67.20,144.39,1,1,...,False,False,True,False,False,False,True,False,True,False
1,18,60786.11,1,22,1,0,71.54,1602.22,2,0,...,True,False,True,False,False,True,False,False,False,False
2,38,73184.32,0,3,0,0,112.20,328.81,4,1,...,False,False,False,False,True,False,True,True,False,False
3,44,40923.78,1,6,1,0,107.49,643.45,3,1,...,False,False,True,False,False,False,True,False,False,False
4,45,36400.94,0,9,1,0,110.05,648.79,3,0,...,False,False,False,True,False,False,True,True,False,False

In [9]:
# Split features and target

X = df.drop("churn", axis=1)

y = df["churn"]

print(X.shape)
print(y.shape)

(1000000, 38)
(1000000,)

In [10]:
from sklearn.model_selection import train_test_split

# Split data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(800000, 38)
(200000, 38)