In [2]:
# =====================================================================
#             MACHINE LEARNING(ML) MODEL
# =====================================================================

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../01_Data/cleaned_data.csv")

df.head()

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,680.0,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [5]:
df = df.drop(columns=[
    "customer_id",
    "signup_date"
])

In [6]:
df = pd.get_dummies(
    df,
    columns=[
        "gender",
        "education",
        "marital_status",
        "contract",
        "payment_method"
    ],
    drop_first=True
)

In [7]:
# Save final dataset after feature engineering

df.to_csv(
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\01_Data\final_dataset.csv",
    index=False
)

In [8]:
X = df.drop("churn", axis=1)

y = df["churn"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_model = LogisticRegression(max_iter=2000)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_log))

Accuracy: 0.899825

In [12]:
# Import Random Forest model
from sklearn.ensemble import RandomForestClassifier

# Import accuracy function
from sklearn.metrics import accuracy_score


# Create Random Forest model
# n_estimators = number of trees
# random_state = for same result every time
# n_jobs = -1 means use all CPU cores

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)


# Train model using training data
rf_model.fit(X_train, y_train)


# Predict using test data
y_pred_rf = rf_model.predict(X_test)


# Print accuracy
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.899835

In [13]:
# Import confusion matrix
from sklearn.metrics import confusion_matrix


# Create confusion matrix
cm = confusion_matrix(y_test, y_pred_rf)


# Print confusion matrix
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[179946     18]
 [ 20015     21]]

In [14]:
# Import classification report
from sklearn.metrics import classification_report


# Print classification report
print("Classification Report:")

print(
    classification_report(
        y_test,
        y_pred_rf
    )
)

Classification Report:
              precision    recall  f1-score   support

           0       0.90      1.00      0.95    179964
           1       0.54      0.00      0.00     20036

    accuracy                           0.90    200000
   macro avg       0.72      0.50      0.47    200000
weighted avg       0.86      0.90      0.85    200000

In [15]:
# Import pandas
import pandas as pd


# Get feature importance from model
importance = rf_model.feature_importances_


# Get feature names
feature_names = X.columns


# Create dataframe for importance
feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": importance
})


# Sort by importance
feat_imp = feat_imp.sort_values(
    by="importance",
    ascending=False
)


# Show top 10 important features
feat_imp.head(10)

                        feature  importance
6                monthlycharges    0.086760
7                  totalcharges    0.084770
1                 annual_income    0.082544
23                 credit_score    0.081375
22  days_since_last_interaction    0.076139
21               avg_monthly_gb    0.073532
0                           age    0.071209
3                        tenure    0.060011
17        customer_satisfaction    0.038554
19            num_service_calls    0.031076

In [16]:
# Save feature importance to CSV

feat_imp.to_csv(
    "../01_Data/feature_importance.csv",
    index=False
)

In [18]:
import joblib

joblib.dump(
    rf_model,
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\3_model\churn_model.pkl"
)

['C:\\Users\\boyal\\OneDrive\\Customer_Churn_Analysis\\3_model\\churn_model.pkl']

In [19]:
joblib.dump(
    scaler,
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\3_model\scaler.pkl"
)

['C:\\Users\\boyal\\OneDrive\\Customer_Churn_Analysis\\3_model\\scaler.pkl']

In [20]:
import pandas as pd

sample_data = pd.DataFrame([
    {
        'age': 30,
        'annual_income': 45000,
        'tenure': 3,
        'monthlycharges': 80,
        'totalcharges': 240,
        'num_services': 2,
        'paperless_billing': 1,
        'senior_citizen': 0,
        'avg_monthly_gb': 40,
        'credit_score': 650
    },
    {
        'age': 55,
        'annual_income': 70000,
        'tenure': 10,
        'monthlycharges': 120,
        'totalcharges': 1200,
        'num_services': 4,
        'paperless_billing': 0,
        'senior_citizen': 1,
        'avg_monthly_gb': 60,
        'credit_score': 720
    }
])

In [21]:
pd.get_dummies(...)

   Ellipsis
0      True

In [23]:
import joblib

model = joblib.load(r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\3_model\churn_model.pkl")

In [33]:
sample_data = X.iloc[[0, 1]]

sample_scaled = scaler.transform(sample_data)

predictions = model.predict(sample_scaled)

for i in predictions:
    if i == 1:
        print(i,"-> Stay")
    else:
        print(i,"-> leave")

0 -> leave
0 -> leave

In [27]:
print(y_test.value_counts())

churn
0    179964
1     20036
Name: count, dtype: int64

In [28]:
sample = X.iloc[[0, 1]].copy()

sample_scaled = scaler.transform(sample)

sample["Actual"] = y.iloc[[0, 1]].values
sample["Predicted"] = rf_model.predict(sample_scaled)

print(sample[["Actual", "Predicted"]])

   Actual  Predicted
0       0          0
1       0          0

In [35]:
churn_samples = X[y == 1].iloc[:5]

churn_scaled = scaler.transform(churn_samples)

predictions = rf_model.predict(churn_scaled)

for i in predictions:
    if i == 0:
        print(i,"-> stay")
    else:
        print(i, "-> churn")

1 -> churn
1 -> churn
1 -> churn
0 -> stay
1 -> churn