In [3]:
# Import libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [4]:
# Load final dataset

df = pd.read_csv(
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\01_Data\final_dataset.csv"
)

df.head()

,age,annual_income,dependents,tenure,paperless_billing,senior_citizen,monthlycharges,totalcharges,num_services,has_phone_service,...,education_master,education_phd,marital_status_married,marital_status_single,marital_status_widowed,contract_one_year,contract_two_year,payment_method_credit_card,payment_method_electronic_check,payment_method_mailed_check
0,43,55085.25,1,2,1,0,67.20,144.39,1,1,...,False,False,True,False,False,False,True,False,True,False
1,18,60786.11,1,22,1,0,71.54,1602.22,2,0,...,True,False,True,False,False,True,False,False,False,False
2,38,73184.32,0,3,0,0,112.20,328.81,4,1,...,False,False,False,False,True,False,True,True,False,False
3,44,40923.78,1,6,1,0,107.49,643.45,3,1,...,False,False,True,False,False,False,True,False,False,False
4,45,36400.94,0,9,1,0,110.05,648.79,3,0,...,False,False,False,True,False,False,True,True,False,False

In [5]:
# Use sample for faster processing

df_sample = df.sample(100000, random_state=42)

X = df_sample.drop("churn", axis=1)

y = df_sample["churn"]

In [6]:
# Split data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
# Train model

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [10]:
# Predict churn

y_pred = rf_model.predict(X_test)

In [11]:
# Create result dataframe

result_df = X_test.copy()

result_df["actual_churn"] = y_test.values

result_df["predicted_churn"] = y_pred

result_df.head()

,age,annual_income,dependents,tenure,paperless_billing,senior_citizen,monthlycharges,totalcharges,num_services,has_phone_service,...,marital_status_married,marital_status_single,marital_status_widowed,contract_one_year,contract_two_year,payment_method_credit_card,payment_method_electronic_check,payment_method_mailed_check,actual_churn,predicted_churn
497582,36,39224.23,0,41,1,0,92.61,2626.22,3,1,...,True,False,False,True,False,False,False,False,0,0
130207,87,42287.78,2,4,1,0,114.64,329.77,4,1,...,False,True,False,False,True,False,True,False,0,0
140703,46,47419.43,3,9,1,1,131.85,1128.77,5,1,...,False,False,True,True,False,True,False,False,0,0
695403,49,56709.19,0,1,0,0,66.66,67.89,3,0,...,False,True,False,False,False,False,False,True,0,0
843558,36,54580.08,3,16,1,0,132.56,2155.77,2,1,...,True,False,False,False,True,True,False,False,0,0

In [12]:
# Save predictions

result_df.to_csv(
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\01_Data\churn_predictions.csv",
    index=False
)

In [13]:
# Feature importance

importance = rf_model.feature_importances_

feature_names = X.columns


feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": importance
})


feat_imp = feat_imp.sort_values(
    by="importance",
    ascending=False
)


feat_imp.to_csv(
    r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\01_Data\feature_importance.csv",
    index=False
)